<?php

namespace Proxies\__CG__\Acme\SiteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hermanos extends \Acme\SiteBundle\Entity\Hermanos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('reffraternidad' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->reffraternidad);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'reffraternidad', 'nick', 'nombre', 'apellidos', 'correo', 'clave', 'nacimiento', 'fallecido', 'biografia', 'telefono', 'vsimples', 'vsolemnes', 'ordenacion', 'lugar', 'fraternidad', 'imagen', 'cargo', 'cargoprov');
        }

        return array('__isInitialized__', 'id', 'nick', 'nombre', 'apellidos', 'correo', 'clave', 'nacimiento', 'fallecido', 'biografia', 'telefono', 'vsimples', 'vsolemnes', 'ordenacion', 'lugar', 'fraternidad', 'imagen', 'cargo', 'cargoprov');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Hermanos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->reffraternidad);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNick()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNick', array());

        return parent::getNick();
    }

    /**
     * {@inheritDoc}
     */
    public function setNick($n)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNick', array($n));

        return parent::setNick($n);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', array());

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($c)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', array($c));

        return parent::setCorreo($c);
    }

    /**
     * {@inheritDoc}
     */
    public function getClave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClave', array());

        return parent::getClave();
    }

    /**
     * {@inheritDoc}
     */
    public function setClave($c)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClave', array($c));

        return parent::setClave($c);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', array($apellidos));

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', array());

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setNacimiento($nacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNacimiento', array($nacimiento));

        return parent::setNacimiento($nacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNacimiento', array());

        return parent::getNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFallecido($fallecido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFallecido', array($fallecido));

        return parent::setFallecido($fallecido);
    }

    /**
     * {@inheritDoc}
     */
    public function getFallecido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFallecido', array());

        return parent::getFallecido();
    }

    /**
     * {@inheritDoc}
     */
    public function setBiografia($biografia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBiografia', array($biografia));

        return parent::setBiografia($biografia);
    }

    /**
     * {@inheritDoc}
     */
    public function getBiografia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiografia', array());

        return parent::getBiografia();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setVsimples($vsimples)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVsimples', array($vsimples));

        return parent::setVsimples($vsimples);
    }

    /**
     * {@inheritDoc}
     */
    public function getVsimples()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVsimples', array());

        return parent::getVsimples();
    }

    /**
     * {@inheritDoc}
     */
    public function setVsolemnes($vsolemnes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVsolemnes', array($vsolemnes));

        return parent::setVsolemnes($vsolemnes);
    }

    /**
     * {@inheritDoc}
     */
    public function getVsolemnes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVsolemnes', array());

        return parent::getVsolemnes();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdenacion($ordenacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdenacion', array($ordenacion));

        return parent::setOrdenacion($ordenacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdenacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdenacion', array());

        return parent::getOrdenacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugar($lugar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugar', array($lugar));

        return parent::setLugar($lugar);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugar', array());

        return parent::getLugar();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraternidad($fraternidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraternidad', array($fraternidad));

        return parent::setFraternidad($fraternidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraternidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraternidad', array());

        return parent::getFraternidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen($imagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', array($imagen));

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', array());

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargo($cargo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargo', array($cargo));

        return parent::setCargo($cargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargo', array());

        return parent::getCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargoprov($cargoprov)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargoprov', array($cargoprov));

        return parent::setCargoprov($cargoprov);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargoprov()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargoprov', array());

        return parent::getCargoprov();
    }

}
